OPENAI_API_KEY = "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"
SPOTIFY_CLIENT_ID = "b5f1c4db03c5469eac7f2ddd3b09be87"
SPOTIFY_CLIENT_SECRET = "aeb7a9e6731545cf85f9b319c4893875"
YOUTUBE_API_KEY = "AIzaSyCyoqm2JfPOhB-6OAGC4OvVEXbYE77md_4"